app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')), 
    path('interview/', include('interview.urls')), 
]

core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('subject/<int:id>/', subject_detail, name='subject_detail'),
    path('signup/', signup, name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]
    

interview/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.interview, name='interview'),
    path('<int:id>/', views.interview_detail, name='interview_detail'),
    path('new_interview/', views.new_interview, name='new_interview'),
]

interview/models.py
from django.db import models
from subject.models import Subject, Question
from django.contrib.auth.models import User

# Create your models here.
class Interview(models.Model):
    name = models.CharField(max_length=255)
    job_description = models.TextField()
    subjects = models.ManyToManyField(Subject)
    learend_quesitons = models.ManyToManyField(Question)
    user = models.ForeignKey(User, related_name="created_interview", on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

subject/models.py
from django.db import models

# Create your models here.
class Subject(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
class Question(models.Model):
    LEVEL_CHOICES = [
        (1, 'FOUNDATIONAL'),
        (2, 'PROFICIENT'),
        (3, 'EXPERT'),
    ]
    subject = models.ForeignKey(Subject, related_name="questions", on_delete=models.CASCADE)
    text = models.TextField()
    answer = models.TextField()
    level = models.IntegerField(choices=LEVEL_CHOICES, default=1)
    
    class Meta:
        ordering = ('id',)

    def __str__(self):
        return self.text

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-5 rounded-xl'

    })) 
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-5 rounded-xl'

    }))


class SignupForm(UserCreationForm):
    class Meta:
        model= User
        fields = ('username', 'email', 'password1','password2')

    username =  forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-5 rounded-xl'

    }))   

    email =  forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email adress',
        'class': 'w-full py-4 px-5 rounded-xl'

    }))  

    password1 =  forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-5 rounded-xl'

    }))  


    password2 =  forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-5 rounded-xl'

    }))     

interview/forms.py
from django import forms

from .models import Interview
from subject.models import Subject

class InterviewForm(forms.ModelForm):
    class Meta:
        model = Interview
        fields = ('name', 'job_description', 'subjects',)

    name =  forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-5 rounded-xl'})
        )
    job_description = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Job Description',
        'class' : 'w-full py-4 px-6 rounded-xl border'
    }))
    subjects = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(attrs={
        'placeholder': 'Subjects',
        'class': 'grid grid-cols-2 gap-4'
    }), queryset=Subject.objects.all())

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.db.models import Count

from subject.models import Subject

from .decorators import redirect_if_authenticated
from .forms import SignupForm, LoginForm

# Create your views here.
def index(request):
    subjects_with_question_count = Subject.objects.annotate(
        question_num=Count('questions')
    ).values(
        'id', 'name', 'description', 'question_num'
    )
    return render(request, 'core/index.html', {
        'subjects': subjects_with_question_count
    })

def subject_detail(request, id):
    # Fetch the subject by id and render a detail template
    subject_detail = get_object_or_404(Subject.objects.prefetch_related('questions'), id=id)
    return render(request, 'core/subject_detail.html', {'subject_detail': subject_detail})

@redirect_if_authenticated
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

def logout_view(request):
    logout(request)
    return redirect('core:index')


@method_decorator(redirect_if_authenticated, name='dispatch')
class CustomLoginView(auth_views.LoginView):
    # Optionally, you can customize template_name or any other properties of LoginView here
    form_class = LoginForm
    template_name = 'core/login.html'

interview/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import F

from subject.models import Question

from .models import Interview
from .forms import InterviewForm


# Create your views here.
@login_required
def interview(request):
    user = request.user
    interviews = Interview.objects.filter(user=user)
    print("interviews", interviews)
    return render(request, 'interview/interview.html', {
        'interviews': interviews
    })
    
@login_required
def interview_detail(request, id):

    user = request.user
    interviews = Interview.objects.filter(user=user)

    # Fetch the interview by id and render a detail template
    interview = get_object_or_404(interviews, id=id)

    if request.method == 'POST':
        if request.POST.getlist('question_id'):
            interview.learend_quesitons.add(int(request.POST.getlist('question_id')[0]))
            interview.save()
        if request.POST.getlist('reset'):
            interview.learend_quesitons.set([])
            interview.save()

    # Annotate a random question with its subject
    random_question = Question.objects.filter(subject__in=interview.subjects.all()).annotate(
        subject__id=F('subject_id'),
        subject_name=F('subject__name'),
        subject_description=F('subject__description'),
        question_id=F('id'),
        question_text=F('text'),
        question_answer=F('answer'),
    ).exclude(id__in=interview.learend_quesitons.values_list('id', flat=True)).order_by('?').first()

    # Prepare the context for rendering
    context = {
        'interview': interview,
        'subject_with_random_question': random_question,
    }
    return render(request, 'interview/interview_detail.html', context)

def new_interview(request):
    if request.method == 'POST':
        form = InterviewForm(request.POST)
        # Extract data from the form
        if form.is_valid():
            name = form.cleaned_data['name']
            job_description = form.cleaned_data['job_description']
            subjects = form.cleaned_data['subjects']

            # Create a new object with the extracted data
            new_object = Interview.objects.create(
                name=name,
                job_description=job_description,
                user=request.user
            )
            new_object.subjects.set(subjects)

            new_object.save()
            return redirect('/interview')
    else:
         form = InterviewForm()

    return render(request, 'interview/new_interview.html', {'form':  form} )

subject/views.py
from django.shortcuts import render

# Create your views here.

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Django App</title>
    <!-- Import Tailwind CSS from CDN -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="{% static 'js/my_script.js' %}"></script>
</head>
<body class="bg-gray-50">
    <header class="text-gray-600 body-font shadow w-full">
        <div class="container mx-auto flex flex-wrap p-2 flex-col md:flex-row items-center">
            <a href="{% url 'core:index' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
                <span class="ml-3 text-xl">Recruter Plus</span>
            </a>

            <div class="flex-1"></div>
            {% if request.user.is_authenticated %}
                <a href="{% url 'core:index' %}" class="p-2 text-gray-900 text-xl rounded {% if request.path == '/' %}bg-[#9ca3af] text-white{% endif %}">Home</a>
                <a href="{% url 'interview' %}" class="p-2 text-gray-900 text-xl rounded {% if '/interview/' in request.path %}bg-[#9ca3af] text-white{% endif %}">My Interviews</a>
                <div class="relative" onclick="toggleUserMenuDropdown()">
                    <a id="user-menu" class="flex items-center px-4 text-gray-900 text-xl cursor-pointer">
                        {{ request.user.username }}
                        {% with email_hash=request.user.email|lower|add:'gravatar' %}
                            <img src="https://www.gravatar.com/avatar/{{ email_hash }}?s=40&d=identicon" alt="Profile Image" class="w-8 h-8 rounded-full ml-2" />
                        {% endwith %}
                    </a>
                    <div id="user-menu-dropdown" class="hidden absolute right-0 z-10 mt-2 w-48 bg-white border rounded-md shadow-lg">
                        <a href="#" class="cursor-not-allowed opacity-50 block px-4 py-2 text-gray-800 hover:bg-gray-200">Profile</a>
                        <a href="#" class="cursor-not-allowed opacity-50 block px-4 py-2 text-gray-800 hover:bg-gray-200">Settings</a>
                        <a href="{% url 'core:logout' %}" class="block px-4 py-2 text-gray-800 hover:bg-gray-200">Logout</a>
                    </div>
                </div>
            {% else %}
                 <a href="{% url 'core:signup' %}" class="px-4 text-gray-900 text-xl">Sign up</a>
                 <a href="{% url 'core:login' %}" class="px-4 text-gray-900 text-xl">Log in</a>  
            {% endif %}
        </div>
    </header>

    {% block content %}
    <!-- Content will be inserted here from child templates -->
    {% endblock %}

</body>
</html>

core/templates/core/index.html
{% extends "base.html" %}

{% block content %}
<div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap -m-4">
        {% for subject in subjects %}
        <div class="p-4 lg:w-1/3">
            <a href="subject/{{ subject.id }}" class="block h-full bg-white p-8 rounded hover:bg-gray-100">
                <div class="h-full">
                    <h1 class="title-font text-lg font-medium text-gray-900 mb-3">{{ subject.name }}</h1>
                    <p class="leading-relaxed mb-3">{{ subject.description }}</p>
                    <p class="leading-relaxed mb-3">({{ subject.question_num }} questions)</p>
                </div>
            </a>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-4 p-5 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-2xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
             <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}   

                {{ form.non_field_errors }}
            </div>
        {% endif %}


        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-4 p-5 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-2xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
             <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}   

                {{ form.non_field_errors }}
            </div>
        {% endif %}


        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/subject_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-2xl font-bold mb-4">{{ subject_detail.name }}</h1>
    <p class="mb-8">{{ subject_detail.description }}</p>
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <h2 class="text-xl font-semibold mb-2">Questions</h2>
        {% for question in subject_detail.questions.all %}
            <div class="mb-4">
                <h3 class="font-semibold text-lg">{{ forloop.counter }}. {{ question.text }}</h3>
                
                   
                <p>{{ question.answer |safe}}</p>
                
            </div>
        {% empty %}
            <p>No questions found for this subject.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap -m-4">
        <!-- Module 1 -->
        {% for subject in subjects %}
        <div class="p-4 lg:w-1/3">
            <a href="subject/{{ subject.id }}" class="h-full bg-white p-8 rounded hover:bg-gray-100">
                <div class="h-full bg-white p-8 rounded">
                    <h1 class="title-font text-lg font-medium text-gray-900 mb-3">{{ subject.name }}</h1>
                    <p class="leading-relaxed mb-3">{{ subject.description }}</p>
                    <p class="leading-relaxed mb-3">({{ subject.question_num }} questions)</p>
                </div>
            </a>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/interview/interview.html
{% extends "base.html" %}

{% block content %}
<div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap -m-4">
        {% for interview in interviews %}
        <div class="p-4 lg:w-1/3">
            <a href="{{ interview.id }}" class="block h-full bg-white p-8 rounded hover:bg-gray-100">
                <div class="h-full">
                    <h1 class="title-font text-lg font-medium text-gray-900 mb-3">{{ interview.name }}</h1>
                    <p class="leading-relaxed mb-3">{{ interview.job_description }}</p>
                </div>
            </a>
        </div>
        {% empty %}
            <div class="p-4 lg:w-1/3">
                <h1> You do not have any interview yet!</h1>
            </div>
        {% endfor %}
    </div>
     <div class="absolute top-12 right-1 p-4">
        <a href="{% url 'new_interview' %}" class="px-4 text-gray-900 text-xl bg-blue-500 py-2 rounded-md inline-block hover:bg-blue-700">New Interview</a>
    </div>
</div>
{% endblock %}

core/templates/interview/interview_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto p-8">
    <div class="w-full p-6 bg-white rounded-lg shadow-md">
        <h1 class="text-3xl font-bold mb-2">Interview: {{ interview.name }}</h1> 
        <p>{{ interview.job_description }}</p>
        <div class="mt-4 p-4 bg-gray-50 rounded">
            {% if subject_with_random_question %}
                <h2 class="text-xl font-semibold mb-2">{{ subject_with_random_question.subject_name }}</h2> 
                <strong><p class="mt-1">{{ subject_with_random_question.question_text }}</p> </strong>
                <div class="mt-2 flex flex-col">
                    <div class="h-48 overflow-y-auto">
                        <p class="text-gray-700">{{ subject_with_random_question.question_answer }}</p>
                    </div>
                    <form method="post" action=".">
                        {% csrf_token %}
                        <input type="hidden" name="question_id" value="{{ subject_with_random_question.question_id }}">
                        <div class="flex justify-end space-x-2"> 
                            <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mt-2 self-end">Mark as learned</button>
                            <button type="button" onclick="window.location.reload();" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2 self-end">Next</button>
                        </div>
                    </form>
                </div>
            {% else %}
                
                <div class="mt-2 flex flex-col">
                    <div class="h-48 overflow-y-auto flex justify-center items-center"> <!-- Updated classes here -->
                        <h2 class="text-xl font-semibold mb-2 text-center">You already learned all questions</h2>
                    </div>
                    <form method="post" action=".">
                        {% csrf_token %}
                        <input type="hidden" name="reset" value="1">
                        <div class="flex justify-end space-x-2">
                            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2 self-end">Reset all questions</button>
                        </div>
                    </form>
                </div>
            {% endif%}
        </div>
    </div>
</div>

<!-- Popup form for new users -->
<div id="popupForm" class="fixed inset-0 bg-gray-900 bg-opacity-75 flex items-center justify-center hidden">
    <div class="bg-white w-80 p-8 rounded-lg shadow-lg">
        <h2 class="text-xl font-semibold mb-4">Welcome to Interviews!</h2>
        <p class="text-gray-700">Here you can learn interview questions. Just click "Next" to move to the next question. If you've learned all questions, you can reset them to learn again.</p>
        <button onclick="closePopup()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-6">Got it!</button>
    </div>
</div>

<!-- Question mark icon to reopen the popup -->
<div id="questionMark" onclick="showPopup()" class="fixed bottom-8 right-8 z-10">
    <div class="w-10 h-10 flex items-center justify-center bg-gray-300 text-gray-900 rounded-full cursor-pointer shadow-md">
        <span class="text-xl font-semibold">?</span>
    </div>
</div>

<script>
    // Function to show the popup for new users
    function showPopup() {
        var popup = document.getElementById("popupForm");
        popup.classList.remove("hidden");
        // Set a flag in localStorage indicating that the user has seen the popup
        localStorage.setItem("popupShown", "true");
    }

    // Function to close the popup
    function closePopup() {
        var popup = document.getElementById("popupForm");
        popup.classList.add("hidden");
    }

    // Check if the user has already seen the popup
    var popupShown = localStorage.getItem("popupShown");

    // Show the popup only if the user is new
    if (!popupShown) {
        showPopup();
    }

    // Function to handle clicks on the question mark icon
    document.getElementById("questionMark").addEventListener("click", function() {
        // Show the popup when the question mark icon is clicked
        showPopup();
    });
</script>

{% endblock %}

core/templates/interview/new_interview.html
{% extends "base.html" %}

{% block content %}
<div class="w-1/2 my-4 p-5 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-2xl">New Interview</h1>

        <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.name }}
            {% if form.name.errors %}
                <div class="m-1 p-1 text-red-500">
                    {{ form.name.errors }}
                </div>
            {% endif %}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Job Description</label><br>
            {{ form.job_description }}
            {% if form.job_description.errors %}
                <div class="m-1 p-1 text-red-500">
                    {{ form.job_description.errors }}
                </div>
            {% endif %}
        </div>

        <div class="mb-3">
            <label for="{{ form.subjects.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-700">Subjects</label>
            {{ form.subjects }}
            {% if form.subjects.errors %}
                <div class="m-1 p-1 text-red-500">
                    {{ form.subjects.errors }}
                </div>
            {% endif %}
        </div>


        {% if form.non_field_errors %}
             <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>

</div>
{% endblock %}

core/templates/subject_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-2xl font-bold mb-4">{{ subject_detail.name }}</h1>
    <p class="mb-8">{{ subject_detail.description }}</p>
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <h2 class="text-xl font-semibold mb-2">Questions</h2>
        {% for question in subject_detail.questions.all %}
            <div class="mb-4">
                <h3 class="font-semibold text-lg">{{ question.question }}</h3>
                <ul class="list-disc pl-5">
                   
                        <li>{{ question.answer }}</li>
                </ul>
            </div>
        {% empty %}
            <p>No questions found for this subject.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}